---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCELphDWgn19z6raZHRiYSQBzogq/LSAl2BaCZ7LiCPAA+EMgO7sa1OxdKGmX8hW7Q3CdWlNOMUlR0khMPjP59xkCQhYh5bXWcnmVtr/HqujXFuZvaS4ZZMOQ8WYX9M+6xqrQ4bKrXFrwKl/vb4aPNQLRqSThzyyHVnT6jKFcwFs3d8JRouSvY7xlF6TDirbwflGEfzS8K4tXVSIN5dUZlOacvuTL+bpFtHfX8FdxLH1aEalf/a/hcnIUrQXsTUI6wIM9rzrd+aU+LgnZs9/qnuoc3PR3C0FnXyRB4KdhxRoYcw/W32J5pg3APhmyuq7wINriZ2aZnI/FBR4UHIJOT0Es+eU4BoCLTZSegH5PsAzBWMCE0WDFZz7jdiPb2RJ+i7Cetj0uC7ivqBVdBd6tvcXWvFNNnFTINEJfASLdmX3gJ8eMqiak6r9B5XvWvmlnGKRJaUw8I4BfnK6iRrjUdVpjZ3cogiEAdMUHej3Eg3hHtHg3VTetoplfWuxOeAv2xQkgHmqjdMUIIDR+0Tqcy8ri3hzhjO5H/zl66xqlPEpBcybm2t5SBN6Rfjd9JFo1JRGP7ce/Ob6KQAbfIbLPZHacdYJW78i2xqB92S+3C3RixO9JrIkQsUlPoM4YGydZcxtO4LCBCIfh0YU9bwMyloc8kcapUXRDgbeGRJj7CChfOl9e26+f8v9rJIyxN9gC1P5IRET6RLJQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
